from parser.unified_parser import UnifiedParser
from Analytics.detection import SecurityDetector
from Analytics.alerts import AlertEngine
from Analytics.ui import render_alert, render_dashboard
from datetime import datetime

# Parse Linux authentication log
up = UnifiedParser("logs/sample_auth.log")
events = up.parse()

detector = SecurityDetector(events)

# Run through AlertEngine to show risk scoring
# Build engine and generate alerts (brute-force threshold set to 5)
engine = AlertEngine(detector)
# generate alerts for all detectors (frequency + time-window)
engine.generate_all_alerts(freq_threshold=2, time_window_threshold=3, time_window_seconds=120)

# Also render the raw detection outputs via the pretty UI so they are visible
# Render all alerts generated by the engine (so panels match the summary)
for alert in engine.get_alerts():
      render_alert(alert, pretty=True)

# small dashboard summary computed from engine alerts
summary = {}
for a in engine.get_alerts():
      sev = a.get('severity', 'LOW')
      summary[sev] = summary.get(sev, 0) + 1
render_dashboard(summary, pretty=True)
